### DISCUSSION TITLE
Use conditionnal in map filter using item list variable

### DISCUSSION THREAD

**Discussion by Fabiosilvero** [pallets/jinja#2011] [Q&A]
Hello,

I'm trying to make the default value for the map() filter dynamic like this (with ansible 2.15) : 

```yaml
- set_fact:
    apache_vhosts:
      - name: foo.example.com
        listen_port: 7080
        ssl: true
      - name: bar.example.com
      - name: tor.example.com
        ssl: true

- debug:
    msg: "{{ apache_vhosts | map(attribute='listen_port', default=apache_default_https_port if item.ssl else apache_default_http_port ) }}"
 ```
 
 The conditionnal works with a `if true` but I can't find the iterator variable like `item` for this function.
 
 
The error I'm facing : 

 ```json
{"msg": "The task includes an option with an undefined variable. The error was: 'item' is undefined. 'item' is undefined\n\nThe error appears to be in '/path/to/file.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug:\n  ^ here\n"} 
 ```
 
 My environment : 
 
 ```ini
 ansible [core 2.15.12]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /app/ansible/venv/lib/python3.12/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /app/ansible/venv/bin/ansible
  python version = 3.12.4 (main, Aug  2 2024, 14:41:31) [GCC 12.2.0] (/app/ansible/venv/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

What am I missing here ?
