### ISSUE TITLE
How to keep multilevel undefined variable not change when jinja2 render?

### ISSUE THREAD

**Issue by mumubin** [pallets/jinja#1120]
I am using jinja2 to render my configuration YAML, then ansible uses the YAML to deploy tasks.
Now I meet one problem I can't handle. 

I have some a template like this:

```yaml
consultPort: 8500

pool: "{{ system.DCName.aa.bb }}-{{system.poolName}}"

database:
  username: "{{ MSecret('helloworld-prod-aa','username') }}"
  password: "{{ MSecret('helloworld-prod-aa','password') }}"
```
After custom render MSecret, the MSecret function works fine ,but it report `system` undefined,Then I add myself PreservedUndefined to skip Undefined to not change, these Undefined variables will be added into the YAML when ansible deploying
```py

def render(to_reader_text):
    from jinja2 import Environment, BaseLoader
    env = Environment(loader=BaseLoader,
                      undefined=PreservedUndefined,
                      )
    context = {}
    context['MSecret'] = MSecret
    template = env.from_string(to_reader_text)
    result = template.render(context)
    return result



START = "{{ "
END = " }}"

class PreservedUndefined(Undefined):

    __slots__ = ()

    def __init__(self, *args, **kwargs):
        super(PreservedUndefined, self).__init__(**kwargs)
    def __getitem__(self, key):

        return self.__str__(key)

    def __getattr__(self, key):
        print "name:" + self._undefined_name
        print "key: " + key
        return self.__str__(key)

    def __str__(self,key):
        if self._undefined_hint is None:

            if self._undefined_obj is missing:
                return u'%s %s.%s %s' % (START, self._undefined_name, key, END)
            return '%s no such element: %s[%r] %s' % (
                START,
                object_type_repr(self._undefined_obj),
                self._undefined_name,
                END
            )
        return u'%s undefined value printed: %s %s' % (self._undefined_hint , START, END)
```
but it only work for only level `system.poolName` not work for `system.DCName.aa.bb`
How to handle `system.DCName.aa.bb`?
I try to  use `ChainableUndefined` from [jinja](https://github.com/pallets/jinja) (maybe not compatiable with Jinja2==2.10.3), but I still can't get the whole name between "{{" and "}}"
```yaml
consultPort: 8500
pool: '{{  no such element: unicode object[''aa'']  }}-{{  system.poolName  }}'
database:
  username: hello
  password: 123

```
