### ISSUE TITLE
Macro doesn't exand list since 3.1.0

### ISSUE THREAD

**Issue by anxstj** [pallets/jinja#1684]
Hello,

I use the following template (`templ.j2`) to create a file with Ansible:
```
---
{%- macro expand_capa(_capa_list) -%}
  {#- use: writes the capa_list object as json list with double ticks -#}
  {#- params: _capa_list is list object of capability strings -#}
  [
  {%- for c in _capa_list -%}
    "{{ c }}"{% if not loop.last %},{% endif %}
  {%- endfor -%}
  ]
{%- endmacro %}

path "x" {
  capabilities = {{ expand_capa(capabilities) }}
}
```
With Jinja2 3.0.3 it creates the following file:
```
---
path "x" {
  capabilities = ["read","write","update","delete"]
}
```

But with Jinja2 3.1.0 it creates a different file:
```
---
path "x" {
  capabilities = ['read', 'write', 'update', 'delete']
}
```

It's similar to the output generated by `capabilities = {{ capabilities }}`. And it looks like the macro gets ignored.

For me, it looks like a bug, because the behavior has changed between two minor versions. I would expect that Jinja2 3.1.0 generates the same file as Jinja2 3.0.3

Environment:

- Python version: 3.10.5
- Jinja version: 3.1.0 and 3.0.3
- Ansible version: 2.13.1

Ansible Playbook:
```
---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: write template
      template:
        src: templ.j2
        dest: output
      vars:
        capabilities:
          - read
          - write
          - update
          - delete
```
