### ISSUE TITLE
extrensionControl breaks out of loop

### ISSUE THREAD

**Issue by raben2** [pallets/jinja#586]
I can not find anything about `extensionControl` being something like a control parameter in Jinja.

When I try to do this loop:

```
{% if app_special_config is defined %}
    {% for item in app_special_config %}
        {% for k, v in item.iteritems() %}
            {% if k == 'name' %}
                {{ v }}:
            {% else %}
                {{ k }}: {{ v }}
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endif %}
```

using this template:

```
app_special_config: 
  - name: upload
    'extensionControl': .ctrl
    filename: TRUSTORLIST
    extension: csv
    uploadDir: outbox
    archiveDir: outbox/archive
    timestampFormat: yyyyMMdd_hhmmss
````

I get this result:

```
    extensionControl: .ctrl
upload:
    extension: csv
    uploadDir: outbox
    timestampFormat: yyyyMMdd_hhmmss
    filename: TRUSTORLIST
    archiveDir: outbox/archive
```

If I change the parameter in my template everything works as expected.

**Comment by ThiefMaster** [comment]
Indentation would make your first snippet more readable...

**Comment by raben2** [comment]
now it should be readable

**Comment by davidism** [comment]
> If I change the parameter in my template everything works as expected.

What parameter do you change?  What do you expect?

**Comment by raben2** [comment]
I change extrensionControl in the template f.e. to test
then i get:
```
# i don't get why this is failing
upload:
    extension: csv
    uploadDir: outbox
    timestampFormat: yyyyMMdd_hhmmss
    filename: TRUSTORLIST
    test: .ctrl
    archiveDir: outbox/archive
```

**Comment by davidism** [comment]
> using this template:

What follows is not a template.  It looks like inconsistently formatted YAML data.  Dictionaries are not ordered, if that's your question.

**Comment by raben2** [comment]
No it is not about the ordering. The extensionControl should be within the upload section but somehow it jumps out.

**Comment by davidism** [comment]
> Dictionaries are not ordered, if that's your question.

If you want keys in a certain order, you need to impose that order.

**Comment by raben2** [comment]
Like i said it is NOT about the ordering.

This is the result i get:
```
    extensionControl: .ctrl
upload:
    extension: csv
    uploadDir: outbox
    timestampFormat: yyyyMMdd_hhmmss
    filename: TRUSTORLIST
    archiveDir: outbox/archive
```
This is what should be happening
```
upload:
    extension: csv
    uploadDir: outbox
    timestampFormat: yyyyMMdd_hhmmss
    filename: TRUSTORLIST
    archiveDir: outbox/archive
```
