### ISSUE TITLE
New line is truncated and new section skipped when line ends with `-%}`

### ISSUE THREAD

**Issue by admix** [pallets/jinja#925]
---

## Expected Behavior
I noticed a weird behavior with the case when the template is divided by sections and one of the serctions end with `-%}` then the next section is actualy becomes a part of the current section.
What I expect to be happening:
template:
```jinja
section_one:
    array_of_keys:
    {% for item in section_one__array_of_keys -%}	   
    - some_key: "{{ item['some_key'] }}"
    {% endfor -%}

section_two:
    key_one: section_two__key_one
    key_two: section_two__key_two
```
expected result once generated:
```yaml
section_one:
    array_of_keys:
    - some_key: 'some_value'
    - some_key: 'some_other_value'

section_two:
    key_one: 'key_one_value'
    key_two: 'key_two_value'

```

## Actual Behavior
the actual result, see that the `section_two` is in the wrong spot now:
```yaml
section_one:
    array_of_keys:
    - some_key: 'some_value'
    - some_key: 'some_other_value'
    section_two:
    key_one: 'key_one_value'
    key_two: 'key_two_value'
```

If the for loop `{% endfor -%}` is not at the end of the section, this doesn't happen.

## Template Code
```jinja
section_one:
    array_of_keys:
    {% for item in section_one__array_of_keys -%}	   
    - some_key: "{{ item['some_key'] }}"
    {% endfor -%}

section_two:
    key_one: section_two__key_one
    key_two: section_two__key_two

```

## Full Traceback
```pytb
N/A

```

## Your Environment
* Python version: `2.7.14`
* Jinja version: `2.8.1`
