### ISSUE TITLE
Nested templates are not filled

### ISSUE THREAD

**Issue by KwisatzHaderach** [pallets/jinja#955]
I'm parsing a yaml which uses nested templates (not sure about correct naming)
```yaml
base: "base"
name: "{{ base }}_ahoj"

one: "{{ name }}"
two: "{{ base }}_cau"
```
and I'm templating this yaml file with jinja like this:
```python
import yaml
from jinja2 import Environment, FileSystemLoader

env = Environment(loader=FileSystemLoader('.'))
template = env.get_template("nested.yaml")
stream = file("nested.yaml", "r")
text = yaml.load(stream)
rendered = template.render(text)
```

## Expected Behavior
```yaml
base: "base"
name: "base_ahoj"

one: "base_ahoj"
two: "base_cau"
```

## Actual Behavior
```yaml
base: "base"
name: "base_ahoj"

one: "{{ base }}_ahoj"
two: "base_cau"
```

## Your Environment
* Python version: Python 2.7.15
* Jinja version: 2.10
